---
- name: add couchdb PPA repository
  become: yes
  apt_repository:
    repo: ppa:couchdb/stable

- name: install couchdb
  become: yes
  apt:
    name: couchdb
  register: couchdb_install

- name: stop couchdb
  become: yes
  service:
    name: couchdb
    state: stopped
  when: couchdb_install.changed

- name: create link to couchdb executable
  file:
    state: link
    mode: 0770
    owner: couchdb
    group: couchdb
    src: /opt/couchdb/bin/couchdb
    path: /usr/bin/couchdb
  when: couchdb_install.changed

- name: secure couchdb installation
  file:
    state: directory
    mode: 0770
    owner: couchdb
    group: couchdb
    path: "{{ item }}"
  with_items:
    - /usr/lib/couchdb
    - /usr/share/couchdb
    - /opt/couchdb
  when: couchdb_install.changed

- name: start couchdb
  become: yes
  service:
    name: couchdb
    state: started
  when: couchdb_install.changed

- name: setup admins
  become: yes
  template:
      src: admins.ini
      dest: /opt/couchdb/etc/local.d/10-admins.ini
      mode: 0770
      owner: couchdb
      group: couchdb
  notify: restart couchdb

- name: create configuration file
  become: yes
  template:
    src: config.ini
    dest: /opt/couchdb/etc/local.d/config.ini
    mode: 0770
    owner: couchdb
    group: couchdb
  notify: restart couchdb
